name: Bin2Chars CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: ${{ matrix.os }} / ${{ matrix.compiler }} / ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          # GCC
          - os: ubuntu-latest
            compiler: GCC
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release

          - os: ubuntu-latest
            compiler: GCC
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Debug

          - os: ubuntu-latest
            compiler: GCC
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Generic 

          # Clang
          - os: ubuntu-latest
            compiler: Clang
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Release

          - os: ubuntu-latest
            compiler: Clang
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Debug

          - os: ubuntu-latest
            compiler: Clang
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Generic

          # MSVC
          - os: windows-latest
            compiler: MSVC
            c_compiler: cl
            cpp_compiler: cl
            build_type: Release

            # Apple Silicon (ARM64)
          - os: macos-latest
            compiler: AppleClang
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Release

          - os: macos-latest
            compiler: AppleClang
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Debug

          - os: macos-latest
            compiler: AppleClang
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Generic 

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Boost.Test - Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev

      - name: Install Boost - Windows
        if: runner.os == 'Windows'
        run: |
          vcpkg install boost-test:x64-windows boost-type-index:x64-windows

      - name: Install Boost.Test - macOS
        if: runner.os == 'macOS'
        run: |
          brew install boost

      - name: Configure CMake - Windows
        if: runner.os == 'Windows'
        run: >
          cmake
          -S .
          -B build
          -DBIN2CHARS_CIBUILD=ON
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Configure CMake - Unix
        if: runner.os != 'Windows'
        run: >
          cmake
          -S .
          -B build
          -DBIN2CHARS_CIBUILD=ON
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: >
          cmake
          --build build
          --config ${{ matrix.build_type }}
          --parallel
          --verbose

      - name: Test
        run: >
          ctest
          --test-dir build
          --build-config ${{ matrix.build_type }}
          --output-on-failure
          --stop-on-failure


      - name: Update CI status badge
        if: ${{ always() && github.ref == 'refs/heads/main' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 10321f35631b9bc6f87ea49be103fbd3
          filename: bin2chars-${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.build_type }}.json
          label: CI
          message: ${{ job.status }}
          color: ${{ job.status == 'success' && 'brightgreen' || 'red' }}
